name: Build and Deploy

on:
  push:
    branches: [ main ]  # or whatever your default branch is named
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10'  # or whatever version you're using
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      env:
        REACT_APP_WEB3FORMS_ACCESS_KEY: ${{ secrets.WEB3FORMS_ACCESS_KEY }}
      run: npm run build

    # Add deployment steps here if needed
    # For example, if you're deploying to GitHub Pages:
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build