name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Or whichever version you prefer

    - name: Install dependencies
      run: npm ci  # This assumes you have a package-lock.json file

    - name: Install Wrangler
      run: npm install -g wrangler@latest

    - name: Deploy to Cloudflare Pages
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_ACCOUNT_EMAIL: ${{ secrets.CF_ACCOUNT_EMAIL }}
      run: wrangler pages deploy . --project-name saquib34.github.io